apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "go-kube-downscaler.configMapName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "go-kube-downscaler.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
data:
  EXCLUDE_NAMESPACES: '{{ join "," (coalesce .Values.excludedNamespaces (list .Release.Namespace "kube-system")) }}'
  {{- if .Values.configMap.extraConfig }}
  {{- tpl .Values.configMap.extraConfig . | nindent 2 }}
  {{- end }}
