{{- with .Values.podDisruptionBudget }}
{{- if and .enabled (or .minAvailable .maxUnavailable) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "go-kube-downscaler.fullname" $ }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "go-kube-downscaler.labels" $ | nindent 4 }}
    app.kubernetes.io/component: controller
spec:
  selector:
    matchLabels:
      {{- include "go-kube-downscaler.selectorLabels" $ | nindent 6 }}
  {{- if .minAvailable }}
  minAvailable: {{ .minAvailable }}
  {{- else }}
  maxUnavailable: {{ .maxUnavailable }}
  {{- end }}
  {{- with .unhealthyPodEvictionPolicy }}
  unhealthyPodEvictionPolicy: {{ . }}
  {{- end }}
{{- end }}
{{- end }}
